export const HIDE_ADD_PROJECT_MODAL = 'HIDE_ADD_PROJECT_MODAL';
export const SHOW_ADD_PROJECT_MODAL = 'SHOW_ADD_PROJECT_MODAL';
export const ARCHIVE_PROJECT = 'ARCHIVE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DUPLICATE_PROJECT = 'DUPLICATE_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const FAVORITED_PROJECT = 'FAVORITED_PROJECT';
export const UNFAVORITED_PROJECT = 'UNFAVORITED_PROJECT';
