export const HIDE_ADD_PROJECT_MODAL = 'HIDE_ADD_PROJECT_MODAL';
export const SHOW_ADD_PROJECT_MODAL = 'SHOW_ADD_PROJECT_MODAL';
export const ARCHIVE_PROJECT = 'ARCHIVE_PROJECT';
export const UNARCHIVE_PROJECT = 'UNARCHIVE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DUPLICATE_PROJECT = 'DUPLICATE_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const FAVORITED_PROJECT = 'FAVORITED_PROJECT';
export const UNFAVORITED_PROJECT = 'UNFAVORITED_PROJECT';
export const SAVE_EDIT_PROJECT = 'SAVE_EDIT_PROJECT';
export const SHOW_EDIT_PROJECT_MODAL = 'SHOW_EDIT_PROJECT_MODAL';
export const HIDE_EDIT_PROJECT_MODAL = 'HIDE_EDIT_PROJECT_MODAL';
export const SHOW_QUICK_TASK_MODAL = 'SHOW_QUICK_TASK_MODAL';
export const HIDE_QUICK_TASK_MODAL = 'HIDE_QUICK_TASK_MODAL';

// tasks actions
export const ADD_TASK_TO_PROJECT = 'ADD_TASK_TO_PROJECT';

// delete project
export const DELETE_PROJECT_CONFIRM = 'DELETE_PROJECT_CONFIRM';
export const DELETE_PROJECT_CANCEL = 'DELETE_PROJECT_CANCEL';

// project comments
export const ADD_COMMENT_TO_PROJECT = 'ADD_COMMENT_TO_PROJECT';
export const EDIT_COMMENT_TO_PROJECT = 'EDIT_COMMENT_TO_PROJECT';
export const DELETE_COMMENT_TO_PROJECT = 'DELETE_COMMENT_TO_PROJECT';
export const DELETE_COMMENT_TO_PROJECT_CONFIRM =
  'DELETE_COMMENT_TO_PROJECT_CONFIRM';
export const DELETE_COMMENT_TO_PROJECT_CANCEL =
  'DELETE_COMMENT_TO_PROJECT_CANCEL';
export const UPDATE_COMMENT_OF_PROJECT = 'UPDATE_COMMENT_OF_PROJECT';
export const UPDATE_TASK_OF_PROJECT = 'UPDATE_TASK_OF_PROJECT';

export const DELETE_TASK_TO_PROJECT = 'DELETE_TASK_TO_PROJECT';
export const DELETE_TASK_TO_PROJECT_CONFIRM = 'DELETE_TASK_TO_PROJECT_CONFIRM';
export const DELETE_TASK_TO_PROJECT_CANCEL = 'DELETE_TASK_TO_PROJECT_CANCEL';

export const MARK_TASK_AS_COMPLETED = 'MARK_TASK_AS_COMPLETED';
export const MARK_TASK_AS_UNCOMPLETED = 'MARK_TASK_AS_UNCOMPLETED';
